api.url.mapping=/api/v1.0.0/pfm

spring.application.name=restapi
server.port=${SERVER_PORT}
logging.level.org.springframework.security=DEBUG

# Database Related Variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app.secret=${SECRET}